### ISSUE TITLE
Problem with GraphQL search 

### ISSUE THREAD

**Issue by diow** [colbyfayock/next-wordpress-starter#143]
https://i.imgur.com/zWFeNcD.png

I am getting error messages on clean install with fresh download.
Honestly I am a bit confused as my .env.local definetely looks okay!

> 
> [SearchIndex] Failed to fetch posts from https://pradera.mkpactive.com/graphql: GraphQL Request must include at least one of those two parameters: "query" or "queryId"
> 
> [Sitemap] Failed to fetch posts from https://pradera.mkpactive.com/graphql: GraphQL Request must include at least one of those two parameters: "query" or "queryId"
> 
> [SocialImages] Failed to fetch posts from https://pradera.mkpactive.com/graphql: GraphQL Request must include at least one of those two parameters: "query" or "queryId"
> 
> [Feed] Failed to fetch metadata from https://pradera.mkpactive.com/graphql: GraphQL Request must include at least one of those two parameters: "query" or "queryId"

WORDPRESS_GRAPHQL_ENDPOINT="https://pradera.mkpactive.com/graphql"
WORDPRESS_HOST="https://pradera.mkpactive.com"

**Comment by colbyfayock** [comment]
hey @diow it looks like you don't have the WPGraphQL plugin installed or you have it  configured at a different endpoint

if you go to https://pradera.mkpactive.com/graphql in your browser, it would look like the following if it was installed

![image](https://user-images.githubusercontent.com/1045274/112628754-b1934280-8e09-11eb-83f4-371ed9523419.png)

**Comment by colbyfayock** [comment]
You can install it right in the WP dashboard https://wordpress.org/plugins/wp-graphql/

**Comment by diow** [comment]
It was installed when I posted this but I have disabled it after that as I was testing various options.
I have now enabled it so please check and try to run the setup yourself specifying my endpoint

**Comment by diow** [comment]
I haven't changed any of the settings - it is the same as per when I have posted this issue

**Comment by diow** [comment]
btw try incognito as redirect automatically will send you to homepage if you have visited that page when I turned off the plugin

**Comment by diow** [comment]
I just created a fresh installation and it worked - thanks I will investigate why the other one wasn't working and I will let you know here

**Comment by colbyfayock** [comment]
glad to hear its working, thanks for the update

**Comment by colbyfayock** [comment]
hey closing this, but let me know if you're still running into any issues!

**Comment by arunsathiya** [comment]
I am running into the same issue on a fresh installation. I have ensured that the site is public and that the endpoint responds [similar to how it does here](https://github.com/colbyfayock/next-wordpress-starter/issues/143#issuecomment-808163100). Any pointers on how to troubleshoot next would be great, thank you!

My site is `https://arun.mystagingwebsite.com/graphql`

**Comment by colbyfayock** [comment]
hey i just tried spinning up a new site and didn't have any issues locally 🤔 

just to make sure, the env var should be:

```
WORDPRESS_GRAPHQL_ENDPOINT="https://arun.mystagingwebsite.com/graphql"
```

![image](https://user-images.githubusercontent.com/1045274/140649836-72516a6d-8018-4fd3-a9fb-473ab999af93.png)

**Comment by arunsathiya** [comment]
I didn't realize node version can have an impact. I was on 14.18.1 but I have updated to 17.0.1 now. However, I have a different issue related to canvas now:

```
➜  ~ yarn create next-app -e https://github.com/colbyfayock/next-wordpress-starter
yarn create v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-next-app@12.0.3" with binaries:
      - create-next-app
✔ What is your project named? … blog
Creating a new Next.js app in /Users/arun/blog.

Downloading files from repo https://github.com/colbyfayock/next-wordpress-starter. This might take a moment.

Installing packages. This might take a couple of minutes.

yarn install v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > nextjs-progressbar@0.0.11" has incorrect peer dependency "next@^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0".
warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] 🔨  Building fresh packages...
[1/2] ⡀ canvas
error /Users/arun/blog/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/arun/blog/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@17.0.1 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/arun/blog/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v102-darwin-unknown-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v102-darwin-unknown-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v102-darwin-unknown-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@17.0.1 (node-v102 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v102-darwin-unknown-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.0
gyp info using node@17.0.1 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.0
gyp info using node@17.0.1 | darwin | x64
gyp info find Python using Python version 3.9.7 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp http GET https://nodejs.org/download/release/v17.0.1/node-v17.0.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v17.0.1/node-v17.0.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v17.0.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v17.0.1/SHASUMS256.txt
(node:44117) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/arun/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/arun/blog/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/arun/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/arun/Library/Caches/node-gyp/17.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/arun/Library/Caches/node-gyp/17.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/arun/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/arun/Library/Caches/node-gyp/17.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/arun/blog/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/arun/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/usr/local/bin/node" "/Users/arun/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/arun/blog/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/arun/blog/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v102" "--python=/usr/local/opt/python@3.9/bin/python3"
gyp ERR! cwd /Users/arun/blog/node_modules/canvas
gyp ERR! node -v v17.0.1
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/arun/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/arun/blog/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/arun/blog/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102 --python=/usr/local/opt/python@3.9/bin/python3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/arun/blog/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 21.1.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/arun/blog/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/arun/blog/node_modules/canvas
node-pre-gyp ERR! node -v v17.0.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /Users/arun/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/arun/blog/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/arun/blog/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102 --python=/usr/local/opt/python@3.9/bin/python3' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this


Aborting installation.
  yarnpkg install has failed.

✨  Done in 17.57s.
```

I'll investigate how to fix this. Thanks for taking a look though, @colbyfayock!

**Comment by colbyfayock** [comment]
try using 12.20.0 (the nextjs min node version), node-canvas via fabric is causing issues with node versions right now

i started working on https://github.com/colbyfayock/next-wordpress-starter/pull/272 to remove fabric to avoid this issue

**Comment by arunsathiya** [comment]
Thanks for the pointer! `create-next-app` seems to require 12.22.0 or higher:

```
➜  ~ yarn create next-app -e https://github.com/colbyfayock/next-wordpress-starter
yarn create v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error create-next-app@12.0.3: The engine "node" is incompatible with this module. Expected version ">=12.22.0". Got "12.20.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

So, that eventually worked. 🎉
