### ISSUE TITLE
Password-protected posts make the build fail: "Apollo Server: Internal server error"

### ISSUE THREAD

**Issue by leoloso** [colbyfayock/next-wordpress-starter#218]
Hi, I'm not able to start the starter, any help will be welcome.

I tried both `npm run dev` on the cloned source, and `npm run build` after running `npx create-next-app ...`, the error happens in both cases.

I installed a local WP site (PHP 7.4, WP 5.8), installed WPGraphQL (1.5.5), endpoint is working on `/graphql`, set it on `.env.local`...

I always get this error:

```
> Build error occurred
Error: Internal server error
    at new ApolloError (/Users/leo/Temporary/starter/nextjs-starter-test/node_modules/@apollo/client/errors/errors.cjs.js:31:28)
    at /Users/leo/Temporary/starter/nextjs-starter-test/node_modules/@apollo/client/core/core.cjs.js:1474:47
    at both (/Users/leo/Temporary/starter/nextjs-starter-test/node_modules/@apollo/client/utilities/utilities.cjs.js:963:53)
    at /Users/leo/Temporary/starter/nextjs-starter-test/node_modules/@apollo/client/utilities/utilities.cjs.js:956:72
    at new Promise (<anonymous>)
    at Object.then (/Users/leo/Temporary/starter/nextjs-starter-test/node_modules/@apollo/client/utilities/utilities.cjs.js:956:24)
    at Object.next (/Users/leo/Temporary/starter/nextjs-starter-test/node_modules/@apollo/client/utilities/utilities.cjs.js:964:49)
    at notifySubscription (/Users/leo/Temporary/starter/nextjs-starter-test/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/Users/leo/Temporary/starter/nextjs-starter-test/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.next (/Users/leo/Temporary/starter/nextjs-starter-test/node_modules/zen-observable/lib/Observable.js:235:7) {
  type: 'ApolloError',
  graphQLErrors: [
    {
      message: 'Internal server error',
      extensions: [Object],
      locations: [Array],
      path: [Array]
    }
  ],
  networkError: null
}
```

You can see it does compile some stuff before. I checked the generated `sitemap.xml` and it works alright, it got the right content from the DB. Then it fails:

<img width="1102" alt="Screenshot 2021-07-29 at 4 30 18 PM" src="https://user-images.githubusercontent.com/1981996/127459997-7da38a7c-e2ff-4ed3-a4fd-3b9fc4fb00ab.png">

Any idea what's going on and how to fix it?

**Comment by colbyfayock** [comment]
do you only have `/graphql` as the environment variable? it needs to be the entire endpoint including the hostname

**Comment by leoloso** [comment]
I have the entire endpoint

**Comment by leoloso** [comment]
I found it! The build fails when there is a password protected post! Check this out:

![nextjs-issue](https://user-images.githubusercontent.com/1981996/127725264-e2e73e5a-3428-472f-829f-b88c5c90ac3d.gif)

**Comment by colbyfayock** [comment]
ah good catch. i didnt expect that particular error for the issue, which is similar to: https://github.com/colbyfayock/next-wordpress-starter/issues/206
