### ISSUE TITLE
Build fails on Vercel due to ZLIB not found

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#259]
### Discussed in https://github.com/colbyfayock/next-wordpress-starter/discussions/257

<div type='discussions-op-text'>

<sup>Originally posted by **spencersmb** October 14, 2021</sup>
I was really interested in this, but I can't seem to get ISG working on Netlify so I was wondering if there is a version that works on Vercel?

Thanks!
Spencer</div>

When importing into Vercel, there's an error during the build process.

This should be able to deploy "as is" with Vercel

**Comment by colbyfayock** [comment]
We can see if this is fixed via https://github.com/colbyfayock/next-wordpress-starter/pull/262

**Comment by colbyfayock** [comment]
Looks like those changes didn't fix it, we're still getting an error when trying to deploy to Vercel:

```
08:31:19.498
Detected Next.js version: 11.1.2
08:31:19.500
Running "yarn run build"
08:31:19.852
yarn run v1.22.11
08:31:19.915
$ next build
08:31:22.688
Error: failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
08:31:22.689
08:31:22.689
> Build error occurred
08:31:22.691
Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /vercel/path0/node_modules/canvas/build/Release/libpng16.so.16)
08:31:22.691
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
08:31:22.692
    at Module.load (internal/modules/cjs/loader.js:950:32)
08:31:22.692
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
08:31:22.692
    at Module.require (internal/modules/cjs/loader.js:974:19)
08:31:22.692
    at require (internal/modules/cjs/helpers.js:93:18)
08:31:22.692
    at Object.<anonymous> (/vercel/path0/node_modules/canvas/lib/bindings.js:3:18)
08:31:22.692
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
08:31:22.692
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
08:31:22.693
    at Module.load (internal/modules/cjs/loader.js:950:32)
08:31:22.699
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
08:31:22.699
  code: 'ERR_DLOPEN_FAILED'
08:31:22.700
}
08:31:22.711
error Command failed with exit code 1.
08:31:22.711
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
08:31:22.733
Error: Command "yarn run build" exited with 1
```
