### ISSUE TITLE
Error after trying to install from Blog post example

### ISSUE THREAD

**Issue by diegoALCE95** [colbyfayock/next-wordpress-starter#285]
Hi, I used the command `npx create-next-app -e https://github.com/colbyfayock/next-wordpress-starter my-blog` from the blog post tutorial and this error showed up:

```
Downloading files from repo https://github.com/colbyfayock/next-wordpress-starter. This might take a moment.

Installing packages. This might take a couple of minutes.


> playwright@1.16.3 install C:\Users\diego\Desktop\Blog Next & WP\my-blog\node_modules\playwright
> node install.js

Downloading Playwright build of chromium v930007 - 99.8 Mb [====================] 100% 0.0s
Playwright build of chromium v930007 downloaded to C:\Users\diego\AppData\Local\ms-playwright\chromium-930007
Downloading Playwright build of ffmpeg v1006 - 1.4 Mb [====================] 100% 0.0s
Playwright build of ffmpeg v1006 downloaded to C:\Users\diego\AppData\Local\ms-playwright\ffmpeg-1006
Downloading Playwright build of firefox v1297 - 74 Mb [====================] 100% 0.0s
Playwright build of firefox v1297 downloaded to C:\Users\diego\AppData\Local\ms-playwright\firefox-1297
Downloading Playwright build of webkit v1564 - 41 Mb [====================] 100% 0.0s
Playwright build of webkit v1564 downloaded to C:\Users\diego\AppData\Local\ms-playwright\webkit-1564

> core-js-pure@3.19.1 postinstall C:\Users\diego\Desktop\Blog Next & WP\my-blog\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> next-wordpress-starter@0.1.0 prepare C:\Users\diego\Desktop\Blog Next & WP\my-blog
> husky install

"WP\my-blog\node_modules\.bin\" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'C:\Users\diego\Desktop\husky\lib\bin.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-wordpress-starter@0.1.0 prepare: `husky install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the next-wordpress-starter@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\diego\AppData\Roaming\npm-cache\_logs\2021-11-20T21_31_21_701Z-debug.log

Aborting installation.
  npm install has failed.
```

Seems like the error was from `husky install`

l'll try to reinstall to see what's going on. 

Node version: v14.17.6
NPM version: 6.14.15

**Comment by colbyfayock** [comment]
hey @diegoALCE95 thats a strange one, just tried myself on node 14.18.1 with no issues. did you ever figure it out?
