### ISSUE TITLE
Local WordPress Instance - ApolloError: Internal server error

### ISSUE THREAD

**Issue by randysmachado** [colbyfayock/next-wordpress-starter#382]
Hi, I'm not able to start my project.
can anybody help me?

I added the GraphQL URL as shown in the tutorial, but there is an error that I couldn't identify.

I'm using WordPress Version 6.0, PHP 7.4.1, Web server nginx.

When I run `yarn dev` the following error occurs

```
ApolloError: Internal server error
    at new ApolloError (C:\developer\grupo-milenio\headless-next\node_modules\@apollo\client\errors\errors.cjs:34:28)
    at C:\developer\grupo-milenio\headless-next\node_modules\@apollo\client\core\core.cjs:1636:47
    at both (C:\developer\grupo-milenio\headless-next\node_modules\@apollo\client\utilities\utilities.cjs:985:53)
    at C:\developer\grupo-milenio\headless-next\node_modules\@apollo\client\utilities\utilities.cjs:978:72
    at new Promise (<anonymous>)
    at Object.then (C:\developer\grupo-milenio\headless-next\node_modules\@apollo\client\utilities\utilities.cjs:978:24)
    at Object.next (C:\developer\grupo-milenio\headless-next\node_modules\@apollo\client\utilities\utilities.cjs:986:49)
    at notifySubscription (C:\developer\grupo-milenio\headless-next\node_modules\zen-observable\lib\Observable.js:135:18)
    at onNotify (C:\developer\grupo-milenio\headless-next\node_modules\zen-observable\lib\Observable.js:179:3)
    at SubscriptionObserver.next (C:\developer\grupo-milenio\headless-next\node_modules\zen-observable\lib\Observable.js:235:7) {
  graphQLErrors: [
    {
      message: 'Internal server error',
      extensions: [Object],
      message: 'Internal server error',
      extensions: [Object],
      locations: [Array],
      path: [Array]
    }
  ],
  clientErrors: [],
  networkError: null,
  extraInfo: undefined
}
```

![error-colby](https://user-images.githubusercontent.com/25080392/176541410-c62bf077-b446-4379-bc4a-a2b355f80cb1.png)

**Comment by colbyfayock** [comment]
hey if you go to that URL in your browser, do you get a GraphQL error? basically to test that it's the right endpoint.

looks like the endpoint is .local which i suspect is a local environment? i haven't tested this on a local WP installation before so not sure how that works if that is the case

**Comment by randysmachado** [comment]
Yes, in the browser the GraphQL URL works the error appears.

I'm using WordPress with Local by Flywheel.

Funny, I tested it with your other basic boilerplate [https://github.com/colbyfayock/next-wpgraphql-basic-starter](https://github.com/colbyfayock/next-wpgraphql-basic-starter) and it worked.

But I wanted to use this project that is already very complete.


![graph-error](https://user-images.githubusercontent.com/25080392/176657256-4ae3cb9a-f200-4e6f-bca1-dd9126fdd46f.png)

**Comment by eibrahimov** [comment]
Hi, I am stuck on this issue. But I deploy WordPress remote host with an SSL domain. Issue exit. 
What are you supposed to do?

**Comment by colbyfayock** [comment]
@eibrahimov if you're hititng a remote source, typically you'll see that error if you do not have your environment variable properly configured. make sure you have `http` or `https` in front of the URL pointing to the GraphQL endpoint

Example: `https://myendpoint.com/graphql`
