### ISSUE TITLE
 NavListItem - Cannot read properties of null

### ISSUE THREAD

**Issue by DasMergo** [colbyfayock/next-wordpress-starter#411]
getting this while using **npm run dev**

> error - src\components\NavListItem\NavListItem.js (12:18) @ NavListItem
error - TypeError: Cannot read properties of null (reading 'includes')
    at NavListItem (webpack-internal:///./src/components/NavListItem/NavListItem.js:25:24)
    at renderWithHooks (C:\Users\DasMergo\wpjs\nasr\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (C:\Users\DasMergo\wpjs\nasr\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (C:\Users\DasMergo\wpjs\nasr\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\Users\DasMergo\wpjs\nasr\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\DasMergo\wpjs\nasr\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\DasMergo\wpjs\nasr\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\Users\DasMergo\wpjs\nasr\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\Users\DasMergo\wpjs\nasr\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\Users\DasMergo\wpjs\nasr\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14) {
  page: '/'
}
  10 |   return (
  11 |     <li key={item.id}>
> 12 |       {!item.path.includes('http') && !item.target && (
     |                  ^
  13 |         <Link href={item.path}>
  14 |           <a title={item.title}>{item.label}</a>
  15 |         </Link>

**Comment by colbyfayock** [comment]
is your graphQL endpoint publicly available? that unfortunately doesn't give much info to try to debug
