### ISSUE TITLE
Server Error => Error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by jatin-rathee** [colbyfayock/next-wordpress-starter#86]
This is what i get when i run command `yarn dev`

```
$ next dev
Loaded env from /mnt/f/Projects/next-wordpress-starter/.env.local
ready - started server on http://localhost:3000
[Feed] Compiling file public/feed.xml
[SearchIndex] Compiling file public/wp-search.json
[Feed] Failed to fetch metadata from http://172.26.32.1/wordpress/graphql: Error: Unexpected token < in JSON at position 0
[SearchIndex] Failed to fetch posts from http://172.26.32.1/wordpress/graphql: Error: Unexpected token < in JSON at position 0
[SearchIndex] Created directory ./public
[SearchIndex] Successfully wrote file to public/wp-search.json
[Feed] Failed to fetch posts from http://172.26.32.1/wordpress/graphql: Error: Unexpected token < in JSON at position 0
[Feed] Created directory ./public
[Feed] Successfully wrote file to public/feed.xml
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
[SearchIndex] Compiling file public/wp-search.json
[Feed] Compiling file public/feed.xml
event - compiled successfully
[SearchIndex] Failed to fetch posts from http://172.26.32.1/wordpress/graphql: Error: Unexpected token < in JSON at position 0
[SearchIndex] Created directory ./public
[Feed] Failed to fetch metadata from http://172.26.32.1/wordpress/graphql: Error: Unexpected token < in JSON at position 0
[SearchIndex] Successfully wrote file to public/wp-search.json
ApolloError: Unexpected token < in JSON at position 0
    at new ApolloError (/mnt/f/Projects/next-wordpress-starter/node_modules/@apollo/client/errors/errors.cjs.js:31:28)
    at /mnt/f/Projects/next-wordpress-starter/node_modules/@apollo/client/core/core.cjs.js:1457:19
    at /mnt/f/Projects/next-wordpress-starter/node_modules/@apollo/client/utilities/utilities.cjs.js:936:69
    at new Promise (<anonymous>)
    at Object.error (/mnt/f/Projects/next-wordpress-starter/node_modules/@apollo/client/utilities/utilities.cjs.js:936:21)
    at notifySubscription (/mnt/f/Projects/next-wordpress-starter/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/mnt/f/Projects/next-wordpress-starter/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/mnt/f/Projects/next-wordpress-starter/node_modules/zen-observable/lib/Observable.js:240:7)
    at /mnt/f/Projects/next-wordpress-starter/node_modules/@apollo/client/utilities/utilities.cjs.js:924:68
    at Array.forEach (<anonymous>) {
  graphQLErrors: [],
  networkError: SyntaxError [ServerParseError]: Unexpected token < in JSON at position 0
      at JSON.parse (<anonymous>)
      at /mnt/f/Projects/next-wordpress-starter/node_modules/@apollo/client/link/http/http.cjs.js:18:25
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    response: Response {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    statusCode: 404,
    bodyText: '<!DOCTYPE html>\r\n' +
      '<html lang="en-US">\r\n' +
      '<head>\r\n' +
      '<meta charset="UTF-8">\r\n' +
      '<meta name="viewport" content="width=device-width, initial-scale=1">\r\n' +
      '<link rel="profile" href="https://gmpg.org/xfn/11">\r\n' +
      '\r\n' +
      '<title>Page not found &#8211; Plants Valley</title>\n' +
      "<link rel='dns-prefetch' href='//fonts.googleapis.com' />\n" +
```

**Comment by colbyfayock** [comment]
hey @jatin-rathee thanks for moving the convo here. do you have WPGraphQL installed on your wordpress instance?

**Comment by jatin-rathee** [comment]
@colbyfayock Thanks, adding WPGraphQL on wordpress fixed my problem
